# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geosud_ref_toa_dialog_base.ui'
#
# Created: Mon Oct  5 01:09:42 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(500, 600)
        Dialog.setMinimumSize(QtCore.QSize(500, 600))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.teParam = QtGui.QTextEdit(self.tab)
        self.teParam.setMinimumSize(QtCore.QSize(0, 0))
        self.teParam.setObjectName(_fromUtf8("teParam"))
        self.gridLayout_2.addWidget(self.teParam, 8, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pbAbout = QtGui.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.pbAbout.setFont(font)
        self.pbAbout.setObjectName(_fromUtf8("pbAbout"))
        self.horizontalLayout_3.addWidget(self.pbAbout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geosudRefToa/icon_geosud.png")))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 10, 0, 2, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setMinimumSize(QtCore.QSize(170, 80))
        self.groupBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.rbRefNorm = QtGui.QRadioButton(self.groupBox)
        self.rbRefNorm.setGeometry(QtCore.QRect(10, 30, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.rbRefNorm.setFont(font)
        self.rbRefNorm.setObjectName(_fromUtf8("rbRefNorm"))
        self.rbRefMilli = QtGui.QRadioButton(self.groupBox)
        self.rbRefMilli.setGeometry(QtCore.QRect(10, 50, 161, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.rbRefMilli.setFont(font)
        self.rbRefMilli.setObjectName(_fromUtf8("rbRefMilli"))
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cbOutput = QtGui.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.cbOutput.setFont(font)
        self.cbOutput.setObjectName(_fromUtf8("cbOutput"))
        self.verticalLayout.addWidget(self.cbOutput)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.pbOutput = QtGui.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.pbOutput.setFont(font)
        self.pbOutput.setObjectName(_fromUtf8("pbOutput"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.pbOutput)
        self.leOutput = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.leOutput.setFont(font)
        self.leOutput.setObjectName(_fromUtf8("leOutput"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.leOutput)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.pbConvert = QtGui.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.pbConvert.setFont(font)
        self.pbConvert.setObjectName(_fromUtf8("pbConvert"))
        self.verticalLayout.addWidget(self.pbConvert)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 9, 0, 1, 1)
        self.pbGetParam = QtGui.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.pbGetParam.setFont(font)
        self.pbGetParam.setObjectName(_fromUtf8("pbGetParam"))
        self.gridLayout_2.addWidget(self.pbGetParam, 7, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.pbLoadImg = QtGui.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.pbLoadImg.setFont(font)
        self.pbLoadImg.setObjectName(_fromUtf8("pbLoadImg"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.pbLoadImg)
        self.leInput = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leInput.sizePolicy().hasHeightForWidth())
        self.leInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.leInput.setFont(font)
        self.leInput.setObjectName(_fromUtf8("leInput"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.leInput)
        self.label_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.pbMetadata = QtGui.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.pbMetadata.setFont(font)
        self.pbMetadata.setObjectName(_fromUtf8("pbMetadata"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.pbMetadata)
        self.leMetadata = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.leMetadata.setFont(font)
        self.leMetadata.setObjectName(_fromUtf8("leMetadata"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.leMetadata)
        self.pbLucky = QtGui.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.pbLucky.setFont(font)
        self.pbLucky.setObjectName(_fromUtf8("pbLucky"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.pbLucky)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.teHistory = QtGui.QTextEdit(self.tab_2)
        self.teHistory.setObjectName(_fromUtf8("teHistory"))
        self.verticalLayout_2.addWidget(self.teHistory)
        self.pbClear = QtGui.QPushButton(self.tab_2)
        self.pbClear.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pbClear.setObjectName(_fromUtf8("pbClear"))
        self.verticalLayout_2.addWidget(self.pbClear)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.glInfo = QtGui.QGridLayout()
        self.glInfo.setObjectName(_fromUtf8("glInfo"))
        self.gridLayout.addLayout(self.glInfo, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Geosud Reflectance TOA", None))
        self.pbAbout.setText(_translate("Dialog", "About", None))
        self.groupBox.setTitle(_translate("Dialog", "Output format", None))
        self.rbRefNorm.setText(_translate("Dialog", "reflectance (32 bits)", None))
        self.rbRefMilli.setText(_translate("Dialog", "milli-reflectance (16 bits)", None))
        self.cbOutput.setText(_translate("Dialog", "output directory (optional)", None))
        self.pbOutput.setText(_translate("Dialog", "...", None))
        self.pbConvert.setText(_translate("Dialog", "Convert DN to TOA", None))
        self.pbGetParam.setText(_translate("Dialog", "Get TOA Parameters", None))
        self.label.setText(_translate("Dialog", "Load image(s)", None))
        self.pbLoadImg.setText(_translate("Dialog", "...", None))
        self.label_2.setText(_translate("Dialog", "Load metadata", None))
        self.pbMetadata.setText(_translate("Dialog", "...", None))
        self.pbLucky.setText(_translate("Dialog", "auto", None))
        self.label_4.setText(_translate("Dialog", "Instrument", None))
        self.comboBox.setItemText(0, _translate("Dialog", "landsat 8", None))
        self.comboBox.setItemText(1, _translate("Dialog", "rapideye", None))
        self.comboBox.setItemText(2, _translate("Dialog", "spot 5", None))
        self.comboBox.setItemText(3, _translate("Dialog", "spot 6/7", None))
        self.comboBox.setItemText(4, _translate("Dialog", "pléiades", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Conversion", None))
        self.pbClear.setText(_translate("Dialog", "Clear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "History", None))

